
name: Trigger DEA Docs Build

on:
  push:
    branches:
      - stable

jobs:
  trigger_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_PAT }}
          repository: GeoscienceAustralia/dea-docs
          event-type: republish-docs